### ISSUE TITLE
conflict with git-plus package

### ISSUE THREAD

**Issue by pdxwolfy** [mark-hahn/tab-smart-sort#6]
There seems to be some sort of issue when both git-plus and tab-smart-sort are installed and enabled. If you try to perform a commit (only tested with Cmd-Shift-A C and Cmd-Shift-A P keyboard shortcuts), the current tab gets changed to the leftmost open tab.  If I disable tab-smart-sort, the current tab is left unchanged. I've already reported this to the author of git-plus, but it's not clear who is stepping on whom.

See the attached clip to see what is happening...
[badtab.zip](https://github.com/mark-hahn/tab-smart-sort/files/72861/badtab.zip)

**Comment by jspiro** [comment]
Can you pull the latest and confirm if this is still an issue?

**Comment by pdxwolfy** [comment]
I apologize for not responding sooner, but this no longer seems to be a problem. Both packages are working properly these days.
